version: '3.6'

services:
  hasura-postgres:
    image: postgres:12
    restart: always
    container_name: hasura-postgres-db
    volumes:
    - ./mounted/postgres-data:/var/lib/postgresql/data
    env_file: env/hasura-postgres.env
    ports:
      - "5434:5434"
    networks:
      - hasura-network
    command: -p 5434

  graphql-engine:
    image: hasura/graphql-engine:v2.16.1
    container_name: hasura-graphql-engine
    ports:
    - "8080:8080"
    depends_on:
    - "hasura-postgres"
    restart: always
    env_file: env/hasura.env
    networks:
      - hasura-network
  
networks:
  hasura-network:
    driver: bridge
